---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: comments-api
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      name: comments-api
  template:
    metadata:
      labels:
        name: comments-api
    spec:
      containers:
      - name: application
        image: "ndobrev/comments-api:latest"
        imagePullPolicy: Always
        ports:
          - containerPort: 8080
        env:
          - name: DB_PORT
            value: "5432"
          - name: DB_HOST
            valueFrom:
              secretKeyRef:
                name: comments-db-secrets
                key: dbHost
          - name: DB_PASSWORD
            valueFrom:
              secretKeyRef:
                  name: comments-db-secrets
                  key: dbPassword
          - name: DB_TABLE
            valueFrom:
              secretKeyRef:
                  name: comments-db-secrets
                  key: dbTable
          - name: DB_USERNAME
            valueFrom:
              secretKeyRef:
                  name: comments-db-secrets
                  key: dbUsername