# apiVersion: v1
# kind: Service
# metadata:
#   name: comments-api
# spec:
#   type: NodePort
#   selector:
#     name: comments-api
#   ports:
#   - protocol: TCP
#     port: 8080
#     targetPort: 8080

# apiVersion: v1
# kind: Service
# metadata:
#   name: comments-api
# spec:
#   selector:
#     app: comments-api
#   ports:
#     - protocol: TCP
#       port: 80
#       targetPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: comments-api
spec:
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  selector:
    name: comments-api
